# Enigma app properties
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/enigma
spring.datasource.username=postgres
spring.datasource.password=enigma
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# OpenAI API Key Configuration
groq.api.key= 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
